version: '3'

services:
  r1bifrost:
    image: jonasal/nginx-certbot:latest
    container_name: r1bifrost
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - "CERTBOT_EMAIL=$CERTBOT_EMAIL"
      - "STAGING=$CERTBOT_STAGING"
    volumes:
      - "$PROXY_PASS_FILE:/etc/nginx/proxy_pass.conf"
      - "$CERTBOT_CERTS_PATH:/etc/letsencrypt"
      - "$SITES_PATH:/etc/nginx/user_conf.d"
      - "$LOGS_PATH:/var/log/nginx"
      - "$UPSTREAM_SSL_CERTS_PATH:/mnt/upstream_ssl_certs"
    networks:
      r1_services:
        ipv4_address: 172.20.2.130

networks:
  r1_services:
    name: r1_services
    driver: bridge
    ipam:
      config:
        # 172.20.2.1-254
        - subnet: 172.20.2.0/24

        # 172.20.2.1-126 (127?)
          ip_range: 172.20.2.0/25
