version: '3.8'

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: fileb
    environment:
      - TZ=America/Mexico_City
      - PUID=$UID
      - PGID=$GID
    volumes:
      - "$PATH_MMEDIA:/srv/mmedia"
      - "$PATH_REDSTORE1:/srv/redstore1"
      - "$PATH_VSTORE:/srv/vstore"
      - "$PATH_DB:/database/filebrowser.db"
      - "$PATH_SETTINGS:/config/settings.json"
    ports:
      - 2001:80
    restart: unless-stopped
    networks:
      - hservices

networks:
  hservices:
    external: true

