
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=America/Mexico_City

      # Following env vars are optional
      - TRANSMISSION_WEB_HOME=/opt/ui/flood-for-transmission
      - USER=${USER}
      - PASS=${PASS}
      # - WHITELIST=iplist #optional
      # - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ${APPDATA_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${WATCH_PATH}:/watch

      - ./config/ui/flood-for-transmission:/opt/ui/flood-for-transmission
    ports:
      - ${PORT_UI}:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - hservices

networks:
  hservices:
    external: true 

