#!/usr/bin/env bash
#
# Checks if spotify is running and prints the
# play char or nothing

IS_RUNNING="$(~/.config/polybar/scripts/spotify/is_running)"
if [ "$IS_RUNNING" != '' ]
then
    STATUS="$(~/.config/polybar/scripts/spotify/controller.py status)"
    if [ "$STATUS" == 'Playing' ]
    then
        echo ""
    else
        echo ""
    fi
else
    echo ""
fi