version: '3.1'

services:
  # This will port forward to all services eventually
  bifrost:
    image: alpine:3.15.4
    container_name: bifrost
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      hservices:
        ipv4_address: 172.20.1.254

  mariadb:
    image: mariadb:10.8.3-jammy
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ${MARIADB_DATA}:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      hservices:
        ipv4_address: 172.20.1.130

  rabbitmq:
    image: rabbitmq:3.9.15-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    environment:
      - 'RABBITMQ_DEFAULT_USER=$RABBITMQ_USER'
      - 'RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS'
    volumes:
      - ${RABBITMQ_DATA}:/var/lib/rabbitmq
    networks:
      hservices:
        ipv4_address: 172.20.1.131

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - '6379:6379'
    networks:
      hservices:
        ipv4_address: 172.20.1.132
        
networks:
  hservices:
    name: hservices
    driver: bridge
    ipam:
      config:
        # 172.20.1-254
        - subnet: 172.20.1.0/24

        # 172.20.1.1-126 (127?)
          ip_range: 172.20.1.0/25

