version: '3.7'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - TZ=America/Mexico_City
      - WORKGROUP=WORKGROUP
      - "USER=$USER;$PASS;$UID;$USER;$GID"
      - USERID=$UID
      - GROUPID=$GID

      - SHARE=blackstore;/mnt/blackstore;yes;no;no
      - SHARE2=redstore;/mnt/redstore;yes;no;no
    ports:
      - '445:445/tcp'
    restart: unless-stopped
    volumes:
      - $BLACKSTORE:/mnt/blackstore
      - $REDSTORE:/mnt/redstore
    command: -p

