version: '3.7'

services:
  samba:
    image: crazymax/samba
    container_name: samba
    network_mode: host
    environment:
      - TZ=America/Mexico_City
      - "SAMBA_LOG_LEVEL=1"
    volumes:
      - $CONFIG:/data
      - $BLACKSTORE:/samba/blackstore
      - $REDSTORE:/samba/redstore
    restart: unless-stopped

