name: infra

services:
  redis:
    image: redis:7.2.0-alpine
    container_name: redis
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    environment:
      - 'RABBITMQ_DEFAULT_USER=$RABBITMQ_USER'
      - 'RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS'
    volumes:
      - ${RABBITMQ_DATA}:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  otelcol:
    image: otel/opentelemetry-collector-contrib
    container_name: otelcol
    ports:
      - 1888:1888   # pprof extension
      - 8888:8888   # Prometheus metrics exposed by the Collector
      - 8889:8889   # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317   # OTLP gRPC receiver
      - 4318:4318   # OTLP http receiver
      - 55679:55679 # zpages extension
    volumes:
      - "./otelcol-cfg.yaml:/etc/otelcol-contrib/config.yaml"

  # Derived from: https://www.jaegertracing.io/docs/1.47/getting-started/#all-in-one
  jaeger:
    image: jaegertracing/all-in-one:1.51
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4300:4317
      - 4301:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

  # See '.env' file for connection params
  neo4j:
    image: neo4j:5.20-community-bullseye
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - "$NEO4J_DATA:/data"

