name: infra

services:
  redis:
    image: redis:7.2.0-alpine
    container_name: redis
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
    environment:
      - 'RABBITMQ_DEFAULT_USER=$RABBITMQ_USER'
      - 'RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS'
    volumes:
      - ${RABBITMQ_DATA}:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  otelcol:
    image: otel/opentelemetry-collector-contrib
    container_name: otelcol
    ports:
      - 1888:1888   # pprof extension
      - 8888:8888   # Prometheus metrics exposed by the Collector
      - 8889:8889   # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317   # OTLP gRPC receiver
      - 4318:4318   # OTLP http receiver
      - 55679:55679 # zpages extension
    volumes:
      - "./otelcol.yaml:/etc/otelcol-contrib/config.yaml"

  # From: https://www.jaegertracing.io/docs/2.5/getting-started/#all-in-one
  jaeger:
    image: jaegertracing/jaeger:2.5.0
    container_name: jaeger
    ports:
      - 16686:16686

      # Already binded in otelcol
      # - 4317:4317
      # - 4318:4318

      - 5778:5778
      - 9411:9411

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - "./config/prometheus.yaml:/etc/prometheus/prometheus.yml"
      - "./data/prometheus:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=90d"
      - "--web.enable-lifecycle"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - "./data/grafana:/var/lib/grafana"
      - "./config/grafana/datasources:/etc/grafana/provisioning/datasources"
      # - "./config/grafana/dashboards:/etc/grafana/provisioning/dashboards"
    environment:
      - "GF_SECURITY_ADMIN_USER=$GRAFANA_USER"
      - "GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_PASS"
      # - GF_INSTALL_PLUGINS= # You can install plugins here if needed
    depends_on:
      - prometheus

  # See '.env' file for connection params
  neo4j:
    image: neo4j:5.20-community-bullseye
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - "$NEO4J_DATA:/data"

  postgres:
    image: postgres:14.6-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5400:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}


