version: '3.8'

services:
  borgmatic:
    image: modem7/borgmatic-docker
    container_name: borgmatic
#    restart: never
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}

      # For rterminal notifications
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_API_PORT=${RABBITMQ_API_PORT}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE}
      - RABBITMQ_ROUTING_KEY=${RABBITMQ_ROUTING_KEY}
    volumes:
      - ${SRC_MMEDIA_CAMERAS}:/mnt/data/mmedia/cameras:ro
      - ${BORG_LOCAL_REPO_PATH}:/mnt/host-local-borg-repository

      - ${BORGMATIC_CFG_PATH}:/etc/borgmatic.d/
      - ${BORG_CFG_PATH}:/root/.config/borg
      - ${BORG_CACHE}:/root/.cache/borg
      - ${SSH_KEYS_PATH}:/root/.ssh
      - ${HOOKS_PATH}:/mnt/hooks

      # Where to restore files when needed?
      - ${RESTORED_PATH}:/mnt/restored
    networks:
      - hservices

networks:
  hservices:
    external: true

