set nocompatible              " be iMproved, required
set encoding=utf-8
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" My plugins list
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Set custom name for dir in '.vim/bundle/*' to prevent name conflicting
" with other plugins (e.g. Dracula theme also is named 'vim')
Plugin 'rose-pine/vim', {'name': 'rose-pine'}


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required


" -----------------------------------------------------------------------------
" Giovanni's custom configuration
"

set laststatus=2                        " Display vim-airline from startup
set number                              " Display line numbers

" Theme config
set background=dark
colorscheme rosepine
let g:airline_powerline_fonts=1         " Use powerline fonts on vim-airline
let g:airline_theme="base16"            " Airline theme

" Tabs configuration
filetype plugin indent on
set tabstop=4                           " Show existing tab with 4 spaces
set shiftwidth=4                        " When indenting with '>' use 4 spaces
set expandtab                           " On pressing tab, insert 4 spaces

" Nerdtree config
set wildignore+=*.pyc,*.o,*.obj,*.svn,*.swp,*.class,*.hg,*.DS_Store,*.min.*
let NERDTreeRespectWildIgnore=1
let NERDTreeShowHidden=1

syntax on

