
services:
  central:
    image: giobyte8/central:1.1.0
    container_name: central
    env_file:
      - central.env
    volumes:
      - "$LOGS_PATH:/opt/central/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"

      - "./central.cfg.yaml:/opt/central/central.cfg.yaml"

      # bifrost proxy_pass config
      - "$BIFROST_PROXY_PASS_TEMPLATE:/opt/central/proxy_pass.jinja"
      - "$BIFROST_PROXY_PASS:/opt/central/proxy_pass.conf"
    networks:
      - r1services

  central-web:
    image: giobyte8/central-web:1.0.0
    container_name: central-web
    restart: unless-stopped
    networks:
      - r1services

networks:
  r1services:
    external: true
