
services:
  central:
    image: giobyte8/central:1.0.0
    container_name: central
    env_file:
      - central.env
    volumes:
      - "$LOGS_PATH:/opt/central/logs"
    networks:
      - r1services

  central-web:
    image: giobyte8/central-web:1.0.0
    container_name: central-web
    restart: unless-stopped
    networks:
      - r1services

networks:
  r1services:
    external: true
