global:
  scrape_interval: 5s       # How frequently to scrape targets by default.
  evaluation_interval: 5s   # How frequently to evaluate rules.

# Alertmanager configuration (optional, can be added later)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093 # Example if you run Alertmanager

scrape_configs:
  - job_name: 'otelcol'
    static_configs:
      - targets: ['otelcol:8889']

  # Promethues scraps itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
