
services:
  rterminal:
    image: giobyte8/rterminal:1.0.3
    container_name: rterminal
    restart: unless-stopped
    user: $UID:$GID
    environment:
      - "TZ=America/Mexico_City"
      - "TG_BOT_TOKEN=${TG_BOT_TOKEN}"
      - "BOT_AUTH_HASH=${BOT_AUTH_HASH}"
      - "SESSION_EXPIRE=${SESSION_EXPIRE}"

      - "REDIS_HOST=${REDIS_HOST}"
      - "REDIS_PORT=${REDIS_PORT}"

      - "RABBITMQ_HOST=${RABBITMQ_HOST}"
      - "RABBITMQ_PORT=${RABBITMQ_PORT}"
      - "RABBITMQ_USER=${RABBITMQ_USER}"
      - "RABBITMQ_PASS=${RABBITMQ_PASS}"

      - "RUNTIME_PATH=/mnt/runtime"
      - "LOG_LEVEL=${LOG_LEVEL}"
    volumes:
      - "${RUNTIME_PATH}:/mnt/runtime"
    networks:
      - hservices

networks:
  hservices:
    external: true

