#!/bin/bash
#
# Note: You can use a cookies.txt file instead of config.json
# by using the cookies param: --cokies cookies.txt
# Just make sure to remove cookies from 'config.json'

gallery-dl                         \
    -c ./gallery-dl.conf.json      \
    -D "./galleries" $1
