services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=America/Mexico_City
    volumes:
      - "$PATH_CONFIG:/config"
      - "$PATH_WALLPAPERS:/mnt/wallpapers"
      - "$PATH_BOOKS:/mnt/books"
      - "$PATH_S20PLUS:/mnt/s20plus"
      - "$PATH_S23_CAM:/mnt/S23_Cam"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - hservices

networks:
  hservices:
    external: true

